### ISSUE TITLE
TaskView was crushed in RecentsActivity

### ISSUE THREAD

**Issue by martincz** [SmartisanTech/android_frameworks_base#2]
遇到了个问题，在最近任务界面中，任务视图的内容会被挤扁。
![image](http://i.imgur.com/fm9P25t.png)
不知道是我在合并过程中出现的问题还是确实存在这样的BUG，如果可行，请帮忙解决或提供点线索，谢谢。
https://github.com/MoKee/android_frameworks_base/tree/mkm

**Comment by zhangjizxc** [comment]
这个是bug ,目测应该是wms 在截屏区域那块逻辑的处理，你可以尝试下fix。我现在有点太忙，你先看看？

**Comment by martincz** [comment]
大体看了下那部分代码，之所以会被压缩就是因为那个statusbar height，结果体现在这张截图上最后一个任务视图底部的黑条。
其实这段逻辑是不必要的，直接使用默认的逻辑就好了，在默认状态或左、右调出OneStep的界面都不会有问题。
这里是修复提交：https://github.com/SmartisanTech/android_frameworks_base/pull/3
当然，你们写的代码可能更明白是为了做什么。如有遗漏，我再改。

**Comment by zhangjizxc** [comment]
Merged. Thanks
