### ISSUE TITLE
When to update framework for android nougat ?

### ISSUE THREAD

**Issue by GuaiYiHu** [SmartisanTech/android_frameworks_base#4]

**Comment by zhangjizxc** [comment]
​we will update it after we release the new phone..​

2017-04-29 10:40 GMT+08:00 乖奕虎 <notifications@github.com>:

**Comment by GuaiYiHu** [comment]
I love smartisan phone. Hope it be better! Fighting!

**Comment by GuaiYiHu** [comment]
Waiting for you to update this fantastic project

**Comment by alone-wolf** [comment]
yep
